### ISSUE TITLE
Include subscription TOPIC as a display option 

### ISSUE THREAD

**Issue by RKF-FKR** [kd8bxp/Wifi_Display_Badge#1]
Hello - this is great work.  Just what I'm after.  I'm using the Lolin32 with the integrated OLED

I wonder if you would consider adding the option to display the TOPIC as well as the subscribed message.

In my case I'm monitoring the garage door state (open or closed). So on the OLED screen it would show:
Garage/Door
OPEN

As well - I'd like to subscribe to ***multiple topics***, (say two or three topics) and have them cycle at a predetermined interval

So in one (say 5 seconds it would show
Garage/Door
OPEN

---then

Hallway/Light
ON

Is that something you would consider for the next revision?
Cheers

**Comment by kd8bxp** [comment]
Sorry it took a while to answer this - multiple topics should be doable. It's not really something I considered. 
You should be able to just add new topics about line 89. 
client.subscribe("display1");
client.subscribe("hallway");
client.subscribe("garage_door");
Line 54 to 73 handle the incoming messages - The way it is now any message from any subscribed topic should get displayed.  This is where some rework would need to take place for a "rotating" display of your topics.
I think you'd probably have to add in some additional variables (Strings one for each topic), do some conditional checks on the topic  ( if topic == "display1" { display1 = msg; } ...
if topic == "hallway" { hallway = msg;} ect... Then probably pull the code that displays the message out and maybe put it in the loop() with some delays between each topic message.
I have thought about having the screen cycle - or recycle the message if nothing else is published.  
It's an interesting idea now that I think about it a little.... feel free to fork the project and give it a go. Let me know how it turns out.
